[package]
name = "ch32-can-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ch32-metapac = { features = [
  "memory-x",
  "rt",
], git = "https://github.com/ch32-rs/ch32-metapac.git", tag = "ch32-data-038b858b45b9b92f4758318f1d746b82427897e9" }
