name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup default nightly
          rustup target add riscv32imac-unknown-none-elf
      - name: Build
        run: cargo build --release --features "__ci" --verbose
      - name: Run tests
        run: cargo test --features "__ci" --verbose
      - name: Build scenarios
        if: always()
        run: |
          for dir in scenarios/*/; do
            echo "Building $dir"
            (cd "$dir" && cargo build)
          done
